version: "3.8"
services:
  grafana:
    restart: always
    image: grafana/grafana:latest
    container_name: grafana
    user: "0" # Root user id, without it we cant use mounts
    ports:
      - 3000:3000
    volumes:
      - "grafana_data:/var/lib/grafana"
    links:
      - influxdb

  influxdb:
    restart: always
    container_name: influxdb
    ports:
      - '8086:8086'
    image: influxdb:2.0.4
    volumes:
      - influxdb_data:/var/lib/influxdb2

  telegraf:
    restart: always
    build: 
      context: ./telegraf/nodemcu/
      dockerfile: Dockerfile
    image: michbud98/telegraf-python:1.0
    container_name: telegraf
    volumes:
      - ./telegraf/nodemcu/telegraf_docker_my.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/nodemcu/get_sensor_data_nodemcu.py:/etc/telegraf/get_sensor_data_nodemcu.py
      - ./telegraf/nodemcu/telegraf_logs:/tmp/
      - ./telegraf/nodemcu/telegraf_logs:/var/log/telegraf/
    links:
      - influxdb 

volumes:
  influxdb_data:
  grafana_data: