version: "3.6"
services:
  
  grafana:
    restart: always
    image: grafana/grafana:latest
    container_name: grafana
    user: "0" # Root user id, without it we cant use mounts
    ports:
      - 3000:3000
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
    links:
      - influxdb

  influxdb:
    restart: always
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      - TZ=Etc/UTC
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_MONITOR_STORE_ENABLED=FALSE
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb2

  nodered:
    restart: always
    build: 
      context: ./nodered
      dockerfile: Dockerfile
    image: michbud98/node-red
    container_name: nodered
    user: "0" # Root user id, without it we cant use mounts
    volumes:
      - ./volumes/nodered/data:/data/
    ports:
      - "1880:1880"

  mariadb:
    restart: always
    image: mariadb
    container_name: mariadb
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - ./volumes/mariadb/data:/var/lib/mysql
    

networks:
  default:
    driver: bridge
    ipam:
      driver: default
    name: TIG

      
