version: '2.0'
services:
  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - 3000:3000
      volumes:
        - "./grafana/grafana_data:/var/lib/grafana"
      links:
        - influxdb
      user: "472"
  influxdb:
    image: influxdb:latest
    container_name: influxdb_database
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/database_files:/var/lib/influxdb
      - ./influxdb/config_files/influxdb.conf:/etc/influxdb/influxdb.conf:ro
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    privileged: true
    volumes:
      - "./telegraf/telegraf_docker.conf:/etc/telegraf/telegraf.conf:ro"
      - "/:/hostfs:ro"
    environment:
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_PROC=/hostfs/proc
    links:
      - influxdb


      