version: "3.8"
services:
  grafana:
    restart: always
    image: grafana/grafana:latest
    container_name: grafana
    user: "0" # Root user id, without it we cant use mounts
    ports:
      - 3000:3000
    volumes:
      - "$PWD/grafana/grafana_data:/var/lib/grafana"
    links:
      - influxdb

  influxdb:
    restart: always
    container_name: influxdb
    ports:
      - '9999:9999'
    image: voidborn/rpi_influxdb2
    volumes:
      - $PWD/influxdb2.0/database_files:/var/lib/influxdb2
      # command which loads data from mount
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt

  telegraf:
    restart: always
    build: 
      context: $PWD/telegraf/nodemcu/
      dockerfile: Dockerfile
    image: michbud98/telegraf-python:1.0
    container_name: telegraf
    volumes:
      - $PWD/telegraf/nodemcu/telegraf_docker_my.conf:/etc/telegraf/telegraf.conf:ro
      - $PWD/telegraf/nodemcu/get_sensor_data_nodemcu.py:/etc/telegraf/get_sensor_data_nodemcu.py
    links:
      - influxdb 
