version: '2.0'
services:
  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - 3000:3000
      volumes:
        - "./grafana/grafana_data:/var/lib/grafana"
      links:
        - influxdb
      user: "472"
  influxdb:
    image: influxdb:latest
    container_name: influxdb_database
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/database_files:/var/lib/influxdb
      - ./influxdb/config_files/influxdb.conf:/etc/influxdb/influxdb.conf:ro


      