version: "3.6"
services:
  
  grafana:
    restart: always
    image: grafana/grafana:latest
    container_name: grafana
    user: "0" # Root user id, without it we cant use mounts
    ports:
      - 3000:3000
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
    links:
      - timescaledb
    
  timescaledb:
    restart: always
    build: 
      context: ./timescaledb
      dockerfile: Dockerfile
    image: michbud98/timescaledb
    container_name: timescaledb
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - ./volumes/timescale/data:/var/lib/postgresql/data

  nodered:
    restart: always
    build: 
      context: ./nodered
      dockerfile: Dockerfile
    image: michbud98/node-red
    container_name: nodered
    user: "0" # Root user id, without it we cant use mounts
    volumes:
      - ./volumes/nodered/data:/data/
    ports:
      - "1880:1880"
    

networks:
  default:
    driver: bridge
    ipam:
      driver: default
    name: TIG

      
