services:
  
  grafana:
    restart: always
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    
  timescaledb:
    restart: always
    build: 
      context: $HOME/Docker-Projects/sensor-stack/timescaledb
      dockerfile: Dockerfile
    image: michbud98/timescaledb:latest-pg16
    container_name: timescaledb
    ports:
      - 5432:5432
    # Stack.env is a file managed by Portainer.
    # Values required:
    # POSTGRES_PASSWORD=example
    env_file: stack.env
    volumes:
      - timescale_data:/var/lib/postgresql/data

  nodered:
    restart: always
    build: 
      context: $HOME/Docker-Projects/sensor-stack/timescaledb
      dockerfile: Dockerfile
    image: michbud98/node-red
    container_name: nodered
    user: "0" # Root user id, without it we cant use mounts
    volumes:
      - nodered_data:/data/
    ports:
      - "1880:1880"
    

networks:
  default:
    driver: bridge
    ipam:
      driver: default
    name: TIG

      
volumes:
  grafana_data:
  timescale_data:
  nodered_data: