version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
  web:
    image: michbud98/django-control-web-app
    build: .
    command: python manage.py runserver 0.0.0.0:$PORT
    env_file: .env
    volumes:
      - ./control_web_app:/app
    ports:
      - "$PORT:$PORT"
    depends_on:
      - db

volumes:
  postgres_data: