version: "3.8"
services:
  influxdb:
    container_name: influxdb
    ports:
      - '9999:9999'
    image: voidborn/rpi_influxdb2
    volumes:
      - $PWD/database_files:/var/lib/influxdb2
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt

